### ISSUE TITLE
tf-serving shows an erorr related to test_model on AWS

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-tf-serving#11]
This issue grew out of vanvalenlab/kiosk#37.

The error shows up repeatedly and is as follows:
`2018-11-19 16:18:35.310041: E tensorflow_serving/util/retrier.cc:37] Reserving resources for servable: {name: test_model version: 0} failed: Not found: Object s3://deepcell-output/models/test_model/0/variables/variables_temp_06f7f1617aed4861978deaebd48c86a3/part-00000-of-00001.data-00000-of-00001.tempstate13412594818431922445 does not exist`

**Comment by willgraf** [comment]
I found an incomplete export in `test_model` inside the bucket.  The python config writer found this file and served it anyway.

---

The python config writer file should identify that this was incomplete.  I've deleted the folder before I thought of this, but there is always a top level `.pb` file that i can look for.  If this is not found, that folder is not a "model".

**Comment by willgraf** [comment]
A new issue has been created (#14) to track the write_config_file.py script enhancement. This issue will be closed, as the test_model error was not caused by a bug, but by an erroneous folder in the bucket.
