### ISSUE TITLE
tf-serving is repeatedly issuing this error in its logs: "2018-11-19 19:53:26.275342: E external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404"

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-tf-serving#7]
This issue grew out of vanvalenlab/kiosk#37 and might be related to vanvalenlab/kiosk-redis-consumer#10.

I've observed this on AWS, but suspect it might happen on both AWS and GKE.

**Comment by willgraf** [comment]
I am 99% sure that these 404 codes are due to the kiosk-redis-consumer liveness check, which pings tf-serving expecting to get a 404 error back.
